version: "3.3"
services:
  go-api-control:
    container_name: go-api-control
    restart: always
    image: go_api_control
    build: ./go-api-control
    ports:
      - "8082:8080"
    environment:
      API_LISTENER_URL: go-api-listener:8080
  go-api-listener:
    container_name: go-api-listener
    restart: always
    image: go-api-listener
    build: ./go-api-listener
    ports:
      - "8080:8080"
  go-api-notification:
    container_name: go-api-notification
    restart: always
    image: go-api-notification
    build: ./go-api-notification
    ports:
      - "8086:8080"
  go-api-business:
    container_name: go-api-business
    restart: always
    image: go-api-business
    build: ./go-api-business
    ports:
      - "8084:8080"
    environment:
      API_LISTENER_URL: go-api-listener:8080
