version: "3.3"
services:
  mongo-db-go:
    container_name: mongo-db-go
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
  mysql-db-go:
    container_name: mysql-db-go
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  rabbit-mq-go:
    container_name: rabbit-mq-go
    image: rabbitmq:3-management
    expose:
     - "5672"
    ports:
     - "15672:15672"
     - "5672:5672"
  keycloak-go:
    container_name: keycloak-go
    image: jboss/keycloak
    ports:
      - 9000:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  go-api-control:
    profiles:
      - donostart
    container_name: go-api-control
    restart: always
    image: go_api_control
    build: ./go-api-control
    ports:
      - "8082:8080"
    depends_on:
      - go-api-listener
    links:
      - go-api-listener
    environment:
      KEYCLOAK_AUTH_URL: http://keycloak-go/auth
      KEYCLOAK_RESOURCE: go-app
      KEYCLOAK_SECRET: tJbyTwUXl7hwr8Nt0O4TEUGceAbFSyE5
      API_LISTENER_URL: go-api-listener:8080
  go-api-listener:
    container_name: go-api-listener
    restart: always
    image: go-api-listener
    build: ./go-api-listener
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db-go
      - rabbit-mq-go
    links:
      - mongo-db-go
      - rabbit-mq-go
    environment:
      MONGO_URI: mongodb://root:root@mongo-db-go:27017
      MONGO_DATABASE: pompeia
      RABBIT_HOST: rabbit-mq-go
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
  go-api-notification:
    container_name: go-api-notification
    restart: always
    image: go-api-notification
    build: ./go-api-notification
    ports:
      - "8086:8080"
    depends_on:
      - mysql-db-go
      - rabbit-mq-go
    links:
      - mysql-db-go
      - rabbit-mq-go
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql-db-go:3306/babilonia?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
      RABBIT_HOST: rabbit-mq-go
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
  go-api-business:
    container_name: go-api-business
    restart: always
    image: go-api-business
    build: ./go-api-business
    ports:
      - "8084:8080"
    depends_on:
      - go-api-listener
    links:
      - go-api-listener
    environment:
      API_LISTENER_URL: go-api-listener:8080
