version: '3.3'
services:
  mongo:
    container_name: "mongo_db_go"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
  mysqlsrv:
    container_name: "mysql_db_go"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
  rabbitmq:
    container_name: "rabbit_mq_go"
    image: rabbitmq:3-management
    expose:
     - "5672"
    ports:
     - "15672:15672"
     - "5672:5672"
  keycloak:
    container_name: "keycloak_go"
    image: jboss/keycloak
    ports:
        - 9000:8080
    environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin