version: "3.3"
services:
  mongo-db-go:
    container_name: mongo-db-go
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
  mysql-db-go:
    container_name: mysql-db-go
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  rabbit-mq-go:
    container_name: rabbit-mq-go
    image: rabbitmq:3-management
    expose:
     - "5672"
    ports:
     - "15672:15672"
     - "5672:5672"
  go-api-control:
    container_name: go-api-control
    restart: always
    image: go_api_control
    build: ./go-api-control
    ports:
      - "8082:8082"
    depends_on:
      - go-api-listener
    links:
      - go-api-listener
    environment:
      KEYCLOAK_AUTH_URL: https://keycloak-go.herokuapp.com/auth
      KEYCLOAK_RESOURCE: go-app
      KEYCLOAK_SECRET: tJbyTwUXl7hwr8Nt0O4TEUGceAbFSyE5
      API_LISTENER_URL: go-api-listener:8080
  go-api-listener:
    container_name: go-api-listener
    restart: always
    image: go-api-listener
    build: ./go-api-listener
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db-go
      - rabbit-mq-go
    links:
      - mongo-db-go
      - rabbit-mq-go
    environment:
      MONGO_URI: mongodb://root:root@mongo-db-go:27017
      MONGO_DATABASE: pompeia
      RABBIT_HOST: rabbitmq
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
  keycloak:
    profiles:
      - donostart
    container_name: "keycloak_go"
    image: jboss/keycloak
    ports:
        - 9000:8080
    environment:
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin